import React from "react";
import Head from "next/head";
import { GetStaticProps } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useQuery } from "react-query";
import { PhotographersService } from "@/api/photographers";
import { Space } from "antd";

import PhotographerCard from "@/components/organism/PhotographerCard/PhotographerCard";
import { t } from "i18next";

const Photographers: React.FC = () => {
  const { data, isLoading } = useQuery("profiles", PhotographersService.getPhotographers);

  return (
    <>
      <Head>
        <title>Photographers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="section">
        <Space style={{ width: "1000px" }} size="large" direction="vertical">
          <h1 className="title">{t("photographers:photographer_msg")}</h1>
          {data?.map((user: any) => (
            <PhotographerCard user={user} key={user._id} />
          ))}
        </Space>
      </section>
    </>
  );
};

export const getStaticProps: GetStaticProps<any> = async ({ locale }: any) => {
  return {
    props: {
      ...(await serverSideTranslations(
        locale,
        ["common", "home", "layout", "sign", "photographers"],
        null,
        ["en", "ro", "ru"],
      )),
    },
  };
};

export default Photographers;
