import Head from "next/head";
import React from "react";
import { useQuery } from "react-query";

import { UsersService } from "@/api/users/users";
import { UserCard } from "@/components/UserCard/UserCard";
import { useAuth } from "@/contextes/AuthContext/useAuth";
import { Spin } from "antd";

const Home: React.FC = () => {
  const [params, setParams] = React.useState<string | null>("");
  const { user } = useAuth();

  React.useEffect(() => {
    const params = localStorage.getItem("Token");
    setParams(params);
  }, []);

  const { data, isLoading } = useQuery(
    ["all-users", params],
    UsersService.getUsers,
    {
      select: (res) => res.data,
    }
  );

  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          padding: "30px 0px 30px 0px",
          backgroundColor: "#d9d9d9",
          minHeight: "100vh",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        {isLoading ? (
          <Spin tip="Loading" size="large" />
        ) : user ? (
          data.map((user: any) => <UserCard info={user} key={user.id} />)
        ) : (
          []
        )}
      </main>
    </>
  );
};

export default Home;
