import HomePageGallery from "@/components/organism/HomePageGallery/HomePageGallery";
import MainCarousel from "@/components/organism/MainCarousel/MainCarousel";
import Head from "next/head";
import React from "react";

const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainCarousel />
        <HomePageGallery />
      </main>
    </>
  );
};

export default Home;
